version: '2'

services:
  nginx:
    image: nginx
    container_name: laravel-project-nginx
    ports:
      - 10080:80
    volumes:
      - ./src:/src
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  php:
    build: ./docker/php
    container_name: laravel-project-php
    volumes:
      - ./src:/src
  mysql:
    build: ./docker/mysql
    container_name: laravel-project-mysql
    restart: always
    environment:
      MYSQL_DATABASE: laravel-project-db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports: 
      - 13306:3306
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./log/mysql:/var/log/mysql
  phpmyadmin:
    container_name: laravel-project-phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - mysql
    ports:
       - 8080:80
    volumes:
       - "./phpmyadmin/sessions:/sessions"
